const ROOM_IMAGES_COUNT = 1;
const APARTMENT_IMAGES_COUNT = 4;
const IMAGE_SIZE = "1024x1024";
const IMAGE_QUALITY = "standard";
const PROMPT_MAX_CHARS = 4000;

module.exports = {
  ROOM_IMAGES_COUNT,
  APARTMENT_IMAGES_COUNT,
  IMAGE_SIZE,
  IMAGE_QUALITY,
  PROMPT_MAX_CHARS,
};
